"""BAX (ABB Advant DB export) line reader for the DB Element pipeline.

BAX files are plain-text engineering exports (``.BAX`` / ``.bax``) generated by
ABB ONB / MasterPiece tools. They already contain DEFAULT blocks, card headers
(``AI1 AI``), and channel objects (``AI1.1``) in the same grammar the PDF AST
compiler expects — so Stage 1 only needs to emit ``LineRecord`` instances.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Callable, List, Optional

from backend.core.logging import get_logger
from backend.parser.pdf_reader import LineRecord

# Comment / section wrappers that carry no engineering parameters.
_BAX_NOISE = re.compile(
    r"^\s*(?:"
    r"\(\*.*?\*\)|"  # (* ... *) including banner lines
    r"BEGIN\b.*|"
    r"END\b.*|"
    r"HEADER\b.*"
    r")\s*$",
    re.IGNORECASE,
)


class BaxReader:
    """
    Stage 1 — BAX text extraction for DB Element listings.

    Produces the same ``List[LineRecord]`` contract as ``PDFReader`` so
    ``ParserService.parse_line_records`` and all downstream stages are reused.
    """

    def __init__(self, job_id: str = None):
        self.logger = get_logger(job_id)

    def extract_line_records(
        self,
        bax_path: Path,
        progress_callback: Optional[Callable[[int, int], None]] = None,
    ) -> List[LineRecord]:
        """Read a BAX export into ordered engineering line records."""
        path = Path(bax_path)
        if not path.exists():
            raise FileNotFoundError(f"BAX file not found: {path}")

        text = self._read_text(path)
        raw_lines = text.splitlines()
        total = max(len(raw_lines), 1)
        records: List[LineRecord] = []

        for idx, raw in enumerate(raw_lines, start=1):
            if progress_callback and (idx == 1 or idx == total or idx % 2000 == 0):
                progress_callback(idx, total)

            line = raw.rstrip("\r\n")
            stripped = line.strip()
            if not stripped:
                continue
            if _BAX_NOISE.match(stripped):
                continue

            records.append(
                LineRecord(
                    page_number=1,
                    line_number=idx,
                    text=stripped,
                )
            )

        if progress_callback:
            progress_callback(total, total)

        self.logger.info(
            f"BaxReader extracted {len(records)} engineering line(s) from {path.name} "
            f"({len(raw_lines)} raw line(s))."
        )
        return records

    @staticmethod
    def _read_text(path: Path) -> str:
        """Decode BAX exports; prefer UTF-8, fall back to Latin-1."""
        data = path.read_bytes()
        if data.startswith(b"\xef\xbb\xbf"):
            return data.decode("utf-8-sig")
        try:
            return data.decode("utf-8")
        except UnicodeDecodeError:
            return data.decode("latin-1")
